Refactor/#11
packed-hexagon/mini-project pull request #21
Opened 2024-07-16 09:47 UTC by rlaxoals36

## 작업 대상

Room 기능
## 📄 작업 내용

Room 관련 Refactor
## 🙋🏻 주의 사항

## 스크린샷

## 📎 관련 이슈

 
#11 
## 레퍼런스

2024-07-16 17:26 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
> +	default List<RoomEntity> getByAccommodation_Id(Long id) {
이 메서드는 default가 필요 없을 것 같아요.

2024-07-16 17:31 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
>  	Optional<RoomEntity> findByAccommodation_IdAndRoomId(Long id, Long roomId);
findByAccommodation_IdAndRoomId() 메서드는 카멜케이스가 아니에요.  저희 컨벤션에 맞지 않아요.

2024-07-16 17:40 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
> +		List<RoomEntity> roomEntityList = this.findByAccommodation_Id(id);
findByAccommodation_Id(id) 메서드는 list를 반환하는데 findAllByAccommodationId(id)가 더 적합해 보여요

2024-07-16 17:46 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
> +		return RoomDto.toDto(roomEntity);
저희 컨벤션에서는 엔티티에서 toDto를 만들기로 했어요.

2024-07-16 17:59 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
>  	public AvailableRoomsRes availableRooms(AvailableRoomsReq req, Long id, Long roomId) {
AvailableRoomsReq req는 멘토님도 지적해주셨던 부분입니다. AvailableRoomsRequest로 수정해주세요.

2024-07-16 18:12 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
> +			: AvailableRoomsRes.builder().reservable(false).build();
이제 room엔티티에 count가 추가되어서 해당 코드는 필요가 없을 것 같아요.
```
roomEntity.getCount() > 0
```
으로 대체하시거나, RoomEntity에서 예약 가능한지 확인하는 메서드를 추가하셔도 좋을 것 같아요.

2024-07-16 18:14 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
> +	default List<RoomEntity> getByAccommodation_Id(Long id) {
이 메서드는 필요 없을 것 같아요.
이해가 힘드시면 구두로 말씀 드릴게요.

2024-07-16 18:17 UTC, tmdeh requested changes
고생하셨습니다.

2024-07-16 19:04 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
>  	public List<RoomDto> findByAccommodationId(Long accommodationId) {
@Transactional(readOnly = true)
이거 추가해주세요

2024-07-16 19:06 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
>  	public RoomDto findByAccommodationIdAndRoomId(Long accommodationId, Long roomId) {
@Transactional(readOnly = true)
이거 추가해주세요

2024-07-16 19:06 UTC, tmdeh commented on src/main/java/com/group6/accommodation/domain/room/service/RoomService.java
>  	public AvailableRoomsRes availableRooms(AvailableRoomsReq req, Long id, Long roomId) {
@Transactional(readOnly = true)
이거 추가해주세요

2024-07-18 01:41 UTC, tmdeh approved these changes

2024-07-18 05:06 UTC, qudwns017 commented on src/main/java/com/group6/accommodation/domain/room/repository/RoomRepository.java
> +		List<RoomEntity> roomEntityList = this.findByAccommodation_Id(id);
내부 jpa Repository는 언더바가 맞지만, 메서드 병은 _Id 일 필요가 없을 것 같습니다.
```default List<RoomEntity> getByAccommodationId(Long id) {```

2024-07-22 07:51 UTC, closed without merging